Don't run unit tests

diff --git a/.github/workflows/build-ilspy.yml b/.github/workflows/build-ilspy.yml
--- a/.github/workflows/build-ilspy.yml
+++ b/.github/workflows/build-ilspy.yml
@@ -62,26 +62,26 @@ jobs:
     - name: Build
       run: msbuild ILSpy.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=$env:BuildPlatform /m
 
-    - name: Execute unit tests
-      run: dotnet test --logger "trx;LogFileName=${{ matrix.configuration }}.trx" --results-directory test-results $env:Tests1 $env:Tests2 $env:Tests3
-      env:
-        Tests1: ICSharpCode.Decompiler.Tests\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\ICSharpCode.Decompiler.Tests.dll
-        Tests2: ILSpy.Tests\bin\${{ matrix.configuration }}\net8.0-windows\ILSpy.Tests.dll
-        Tests3: ILSpy.BamlDecompiler.Tests\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\ILSpy.BamlDecompiler.Tests.dll
+    # - name: Execute unit tests
+    #   run: dotnet test --logger "trx;LogFileName=${{ matrix.configuration }}.trx" --results-directory test-results $env:Tests1 $env:Tests2 $env:Tests3
+    #   env:
+    #     Tests1: ICSharpCode.Decompiler.Tests\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\ICSharpCode.Decompiler.Tests.dll
+    #     Tests2: ILSpy.Tests\bin\${{ matrix.configuration }}\net8.0-windows\ILSpy.Tests.dll
+    #     Tests3: ILSpy.BamlDecompiler.Tests\bin\${{ matrix.configuration }}\net8.0-windows\win-x64\ILSpy.BamlDecompiler.Tests.dll
 
-    - name: Upload Test Logs
-      uses: actions/upload-artifact@v4
-      if: success() || failure()
-      with:
-        name: test-results-${{ matrix.configuration }}
-        path: 'test-results/${{ matrix.configuration }}.trx'
+    # - name: Upload Test Logs
+    #   uses: actions/upload-artifact@v4
+    #   if: success() || failure()
+    #   with:
+    #     name: test-results-${{ matrix.configuration }}
+    #     path: 'test-results/${{ matrix.configuration }}.trx'
 
-    - name: Create Test Report
-      uses: icsharpcode/test-summary-action@dist
-      if: always()
-      with:
-        paths: "test-results/${{ matrix.configuration }}.trx"
-        folded: true
+    # - name: Create Test Report
+    #   uses: icsharpcode/test-summary-action@dist
+    #   if: always()
+    #   with:
+    #     paths: "test-results/${{ matrix.configuration }}.trx"
+    #     folded: true
 
     - name: Format check
       run: dotnet-format whitespace --verify-no-changes --verbosity detailed ILSpy.sln
